import { StyleSheet } from 'react-native';
import { PREMIUM_LIGHT, TOKENS } from './tokens';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: PREMIUM_LIGHT.bg,
  },
  header: {
    backgroundColor: PREMIUM_LIGHT.accent,
    paddingVertical: 20,
    paddingHorizontal: 16,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.35)',
    ...TOKENS.shadow.soft,
  },
  headerTitle: {
    fontSize: 26,
    fontWeight: 'bold',
    color: '#FFFFFF',
    textAlign: 'center',
  },
  card: {
    backgroundColor: PREMIUM_LIGHT.surface,
    borderRadius: 12,
    padding: 16,
    margin: 16,
    borderWidth: 0,
    ...TOKENS.shadow.soft,
  },
  button: {
    backgroundColor: PREMIUM_LIGHT.accent,
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: 16,
    alignItems: 'center',
    marginVertical: 8,
    flexDirection: 'row',
    justifyContent: 'center',
    minHeight: 52,
    ...TOKENS.shadow.strong,
  },
  buttonSecondary: {
    backgroundColor: PREMIUM_LIGHT.surface,
    borderWidth: 1,
    borderColor: 'rgba(255,138,0,0.35)',
    shadowOpacity: 0.12,
  },
  buttonDanger: {
    backgroundColor: PREMIUM_LIGHT.danger,
  },
  buttonText: {
    color: '#FFFFFF',
    fontSize: 17,
    fontWeight: '900',
    letterSpacing: 0.2,
  },
  buttonTextOnDark: {
    color: PREMIUM_LIGHT.accent,
    fontSize: 17,
    fontWeight: '900',
    letterSpacing: 0.2,
  },
  input: {
    borderWidth: 1,
    borderColor: 'rgba(15,23,42,0.16)',
    borderRadius: 14,
    padding: 12,
    fontSize: 16,
    marginVertical: 8,
    backgroundColor: PREMIUM_LIGHT.surface,
    color: PREMIUM_LIGHT.text,
  },
  inputError: {
    borderColor: PREMIUM_LIGHT.danger,
  },
  label: {
    fontSize: 14,
    fontWeight: '800',
    marginBottom: 4,
    color: PREMIUM_LIGHT.text,
  },
  errorText: {
    color: PREMIUM_LIGHT.danger,
    fontSize: 12,
    marginTop: 4,
  },
  successText: {
    color: PREMIUM_LIGHT.success,
    fontSize: 12,
    marginTop: 4,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: PREMIUM_LIGHT.bg,
  },
  loadingText: {
    marginTop: 16,
    fontSize: 16,
    color: PREMIUM_LIGHT.muted,
  },
  emptyState: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  emptyStateText: {
    fontSize: 16,
    color: PREMIUM_LIGHT.muted,
    textAlign: 'center',
    marginTop: 8,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: PREMIUM_LIGHT.border,
  },
  rowLast: {
    borderBottomWidth: 0,
  },
  title: {
    fontSize: 20,
    fontWeight: '800',
    color: PREMIUM_LIGHT.text,
  },
  subtitle: {
    fontSize: 15,
    color: PREMIUM_LIGHT.muted,
    marginTop: 2,
    lineHeight: 20,
  },
  statusBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    fontSize: 12,
    fontWeight: 'bold',
  },
  statusPending: {
    backgroundColor: '#FFF3E0',
    color: '#F57C00',
  },
  statusAssigned: {
    backgroundColor: '#E3F2FD',
    color: '#1976D2',
  },
  statusInProgress: {
    backgroundColor: '#E8F5E8',
    color: '#388E3C',
  },
  statusCompleted: {
    backgroundColor: '#E8F5E8',
    color: '#388E3C',
  },
  statusEmergency: {
    backgroundColor: '#FFEBEE',
    color: '#D32F2F',
  },
  avatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: PREMIUM_LIGHT.accentSoft,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
    borderWidth: 1,
    borderColor: 'rgba(255,138,0,0.30)',
  },
  avatarText: {
    color: PREMIUM_LIGHT.accent,
    fontSize: 20,
    fontWeight: 'bold',
  },
  mapContainer: {
    height: 200,
    borderRadius: 12,
    overflow: 'hidden',
    marginVertical: 16,
  },
  map: {
    flex: 1,
  },
  photoGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    margin: -4,
  },
  photoItem: {
    width: '50%',
    aspectRatio: 1,
    margin: 2,
    borderRadius: 8,
    overflow: 'hidden',
  },
  photo: {
    flex: 1,
    width: '100%',
    height: '100%',
  },
  progressContainer: {
    marginVertical: 16,
  },
  progressHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  progressTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: PREMIUM_LIGHT.text,
  },
  progressSteps: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 8,
  },
  progressStep: {
    flex: 1,
    alignItems: 'center',
    position: 'relative',
  },
  progressStepActive: {
    color: PREMIUM_LIGHT.accent,
  },
  progressStepCompleted: {
    color: PREMIUM_LIGHT.accent,
  },
  progressStepInactive: {
    color: PREMIUM_LIGHT.subtle,
  },
  progressDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: PREMIUM_LIGHT.border,
    marginVertical: 8,
  },
  progressDotActive: {
    backgroundColor: PREMIUM_LIGHT.accent,
  },
  progressDotCompleted: {
    backgroundColor: PREMIUM_LIGHT.accent,
  },
  progressLine: {
    position: 'absolute',
    top: 14,
    left: 50,
    right: -50,
    height: 2,
    backgroundColor: PREMIUM_LIGHT.border,
    zIndex: -1,
  },
  progressLineCompleted: {
    backgroundColor: PREMIUM_LIGHT.accent,
  },
  // Clean stepper (DriverProgress)
  stepperRow: {
    paddingVertical: 8,
    paddingHorizontal: 6,
    alignItems: 'center',
  },
  stepperItem: {
    width: 88,
    alignItems: 'center',
  },
  stepperDot: {
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: PREMIUM_LIGHT.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepperDotActive: {
    backgroundColor: PREMIUM_LIGHT.accent,
  },
  stepperDotCompleted: {
    backgroundColor: PREMIUM_LIGHT.accent,
  },
  stepperCheck: {
    color: '#fff',
    fontSize: 10,
    fontWeight: '900',
    marginTop: -1,
  },
  stepperLabel: {
    marginTop: 8,
    fontSize: 12,
    lineHeight: 14,
    textAlign: 'center',
    color: PREMIUM_LIGHT.muted,
    fontWeight: '800',
  },
  stepperLabelActive: {
    color: PREMIUM_LIGHT.accent,
  },
  stepperLabelCompleted: {
    color: PREMIUM_LIGHT.accent,
  },
  stepperConnector: {
    height: 2,
    width: 22,
    backgroundColor: PREMIUM_LIGHT.border,
    marginHorizontal: 6,
    marginTop: -18,
  },
  stepperConnectorCompleted: {
    backgroundColor: PREMIUM_LIGHT.accent,
  },
  chartContainer: {
    height: 300,
    marginVertical: 16,
  },
  statisticsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 12,
    marginBottom: 8,
    marginHorizontal: -6,
  },
  statisticCard: {
    flexBasis: '50%',
    flexGrow: 1,
    margin: 6,
    paddingVertical: 14,
    paddingHorizontal: 10,
    minHeight: 86,
    backgroundColor: PREMIUM_LIGHT.surface,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 2,
    borderWidth: 0,
    ...TOKENS.shadow.soft,
  },
  statisticValue: {
    fontSize: 22,
    fontWeight: 'bold',
    color: PREMIUM_LIGHT.accent,
    textAlign: 'center',
  },
  statisticLabel: {
    fontSize: 12,
    color: PREMIUM_LIGHT.muted,
    marginTop: 4,
    textAlign: 'center',
    lineHeight: 16,
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: PREMIUM_LIGHT.surface,
    borderRadius: 14,
    paddingHorizontal: 12,
    marginVertical: 8,
    borderWidth: 1,
    borderColor: PREMIUM_LIGHT.border,
  },
  searchIcon: {
    marginRight: 8,
    color: PREMIUM_LIGHT.muted,
  },
  searchInput: {
    flex: 1,
    fontSize: 16,
    paddingVertical: 8,
    color: PREMIUM_LIGHT.text,
  },
  filterContainer: {
    flexDirection: 'row',
    marginVertical: 8,
  },
  filterButton: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 999,
    marginRight: 8,
    fontSize: 12,
    fontWeight: 'bold',
    borderWidth: 1,
    borderColor: PREMIUM_LIGHT.border,
    overflow: 'hidden',
  },
  filterButtonActive: {
    backgroundColor: PREMIUM_LIGHT.accent,
    color: '#FFFFFF',
    borderColor: 'rgba(255,138,0,0.35)',
  },
  filterButtonInactive: {
    backgroundColor: PREMIUM_LIGHT.surface,
    color: PREMIUM_LIGHT.text,
  },
  vehicleCard: {
    backgroundColor: PREMIUM_LIGHT.surface,
    borderRadius: 12,
    padding: 16,
    marginVertical: 8,
    elevation: 2,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 0,
    ...TOKENS.shadow.soft,
  },
  vehicleIcon: {
    width: 60,
    height: 60,
    borderRadius: 12,
    backgroundColor: PREMIUM_LIGHT.accentSoft,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
    borderWidth: 1,
    borderColor: 'rgba(255,138,0,0.22)',
  },
  vehicleInfo: {
    flex: 1,
  },
  vehicleNumber: {
    fontSize: 18,
    fontWeight: 'bold',
    color: PREMIUM_LIGHT.text,
  },
  vehicleDetails: {
    fontSize: 14,
    color: PREMIUM_LIGHT.muted,
    marginTop: 4,
  },
  vehicleStatus: {
    position: 'absolute',
    top: 8,
    right: 8,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    fontSize: 10,
    fontWeight: 'bold',
  },
  workRequestCard: {
    backgroundColor: PREMIUM_LIGHT.surface,
    borderRadius: 12,
    padding: 16,
    marginVertical: 8,
    elevation: 2,
    borderWidth: 0,
    ...TOKENS.shadow.soft,
  },
  workRequestHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  workRequestType: {
    fontSize: 16,
    fontWeight: 'bold',
    color: PREMIUM_LIGHT.text,
  },
  workRequestLocation: {
    fontSize: 14,
    color: PREMIUM_LIGHT.muted,
    marginTop: 4,
  },
  workRequestDuration: {
    fontSize: 14,
    color: PREMIUM_LIGHT.success,
    fontWeight: 'bold',
    marginTop: 4,
  },
  driverCard: {
    backgroundColor: PREMIUM_LIGHT.surface,
    borderRadius: 12,
    padding: 16,
    marginVertical: 8,
    elevation: 2,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 0,
    ...TOKENS.shadow.soft,
  },
  driverInfo: {
    flex: 1,
  },
  driverName: {
    fontSize: 16,
    fontWeight: 'bold',
    color: PREMIUM_LIGHT.text,
  },
  driverContact: {
    fontSize: 14,
    color: PREMIUM_LIGHT.muted,
    marginTop: 4,
  },
  attendanceCard: {
    backgroundColor: PREMIUM_LIGHT.surface,
    borderRadius: 12,
    padding: 16,
    marginVertical: 8,
    elevation: 2,
    borderWidth: 0,
    ...TOKENS.shadow.soft,
  },
  attendanceHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  attendanceDate: {
    fontSize: 16,
    fontWeight: 'bold',
    color: PREMIUM_LIGHT.text,
  },
  attendanceHours: {
    fontSize: 14,
    color: PREMIUM_LIGHT.success,
    fontWeight: 'bold',
  },
  attendanceSite: {
    fontSize: 14,
    color: PREMIUM_LIGHT.muted,
    marginTop: 4,
  },
  reportCard: {
    backgroundColor: PREMIUM_LIGHT.surface,
    borderRadius: 12,
    padding: 16,
    marginVertical: 8,
    elevation: 2,
    borderWidth: 0,
    ...TOKENS.shadow.soft,
  },
  reportHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  reportTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: PREMIUM_LIGHT.text,
  },
  reportDate: {
    fontSize: 14,
    color: PREMIUM_LIGHT.muted,
  },
  reportValue: {
    fontSize: 24,
    fontWeight: 'bold',
    color: PREMIUM_LIGHT.success,
    marginTop: 8,
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalContent: {
    backgroundColor: PREMIUM_LIGHT.surface,
    borderRadius: 12,
    padding: 24,
    width: '90%',
    maxHeight: '80%',
    borderWidth: 0,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: PREMIUM_LIGHT.text,
  },
  modalClose: {
    fontSize: 24,
    color: PREMIUM_LIGHT.muted,
  },
  modalButton: {
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    alignItems: 'center',
    marginVertical: 8,
  },
  modalButtonPrimary: {
    backgroundColor: PREMIUM_LIGHT.accent,
  },
  modalButtonSecondary: {
    backgroundColor: PREMIUM_LIGHT.accentSoft,
    borderWidth: 1,
    borderColor: 'rgba(255,138,0,0.35)',
  },
  modalButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  modalButtonTextSecondary: {
    color: PREMIUM_LIGHT.text,
  },
  toastContainer: {
    position: 'absolute',
    bottom: 20,
    left: 20,
    right: 20,
    alignItems: 'center',
  },
  toast: {
    backgroundColor: '#333',
    color: '#fff',
    padding: 12,
    borderRadius: 8,
    paddingHorizontal: 16,
    maxWidth: '90%',
  },
  toastSuccess: {
    backgroundColor: '#4CAF50',
  },
  toastError: {
    backgroundColor: '#f44336',
  },
  toastWarning: {
    backgroundColor: '#FF9800',
  },
  toastInfo: {
    backgroundColor: '#2196F3',
  },
});

export default styles;